server:
  port: 8088
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
      # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  #ssl:
    #key-store: classpath:4614194_itservice.chint-eletech.com.pfx
    #key-store-password: UjUr25z8  #p12 ：aqjcpt  pfx: UjUr25z8 要用绝对路径
    #key-store-type: PKCS12
    #key-alias: tomcat

# log
logging:
  config: classpath:logback-spring.xml

# sql server
spring:
  datasource:
    url: jdbc:sqlserver://111.229.83.180:1433;DatabaseName=apply #Chint.Hygiene
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: test
    password: 2020
    #连接池配置
    dbcp2:
      initial-size: 5
      max-wait-millis: 60000
      max-idle: 5
      max-total: 50
  resources:
    static-locations: classpath:/,classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
  mvc:
    static-path-pattern: /**
# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zt.entity

# WeChat


